const Business41 = () => {
 return (
  <div className="lecture-common">
   <div className="header header-cyan">
    <h1>
     🔄 Lecture 41 — OTC Process, MRP Concept &amp; Standard Sales Process
    </h1>
    <p>
     SAP SD | The full Order-to-Cash cycle across SD/MM/PP/FI, how MRP
     automatically triggers purchasing, and the Enquiry → Quotation → Sales
     Order documents with their legal significance and background activities
    </p>
   </div>
   <div className="container">
    {/* <!-- Section 0: Recap --> */}
    <div className="card">
     <h2><span className="badge">↩️</span> Where We Left Off</h2>
     <div className="callout blue">
      💡 Last class covered the Structure of a Sales Document and the full
      list of standard Sales Document Types. Today begins Business Processes
      properly with the
      <strong>OTC (Order to Cash) process</strong> — the complete,
      cross-module cycle — then explains how
      <strong>MRP</strong> automatically drives purchasing, and finally
      walks through the <strong>Standard Sales Process</strong>
      document by document: Enquiry, Quotation, and Sales Order.
     </div>
    </div>

    {/* <!-- Section 1: OTC Process Overview --> */}
    <div className="card teal">
     <h2>
      <span className="badge">1</span> OTC Process (Order to Cash) —
      Overview
     </h2>
     <div className="callout teal">
      💡 <strong>OTC (Order to Cash)</strong> is the complete, end-to-end
      cycle from the customer placing an order to the company receiving
      payment — covering everything that can happen in between, including
      production and procurement, not just the sales-only Enquiry-to-Invoice
      flow.
     </div>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>Abbreviation</th>
        <th>Full Form</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>TOR</td>
        <td>Transfer of Requirements</td>
       </tr>
       <tr>
        <td>MRP</td>
        <td>Materials Requirement Planning</td>
       </tr>
       <tr>
        <td>FG</td>
        <td>Finished Goods</td>
       </tr>
       <tr>
        <td>RM</td>
        <td>Raw Materials</td>
       </tr>
       <tr>
        <td>PR</td>
        <td>
         Purchase Requisition — a request to purchase goods,
         auto-generated by the system when a required raw material's
         stock is insufficient
        </td>
       </tr>
       <tr>
        <td>PO</td>
        <td>
         Purchase Order — the PR converted and finalized, then sent to
         the vendor
        </td>
       </tr>
       <tr>
        <td>MIGO</td>
        <td>
         Movement In, Goods Out (Goods Receipt) — posted when the
         vendor's supplied goods are received
        </td>
       </tr>
      </tbody>
     </table>
    </div>

    {/* <!-- Section 2: OTC Process Flow / Three Scenarios --> */}
    <div className="card orange">
     <h2>
      <span className="badge">2</span> OTC Process Flow — Three Scenarios
     </h2>
     <div className="callout orange">
      💡 The process always starts the same way:
      <strong
      >Customer places order → System transfers requirements to MRP (TOR)
       → MRP runs</strong
      >. What happens next depends on stock availability.
     </div>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>Scenario</th>
        <th>Condition</th>
        <th>Resulting Flow</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>1</td>
        <td>Finished Goods stock is available</td>
        <td>Order Confirmation → Delivery → Invoice → Customer pays</td>
       </tr>
       <tr>
        <td>2</td>
        <td>FG not available, but Raw Material stock is available</td>
        <td>
         Production → Quality Check → Unrestricted Stock → Order
         Confirmation → Delivery → Invoice → Customer pays
        </td>
       </tr>
       <tr>
        <td>3</td>
        <td>Neither FG nor RM stock is available</td>
        <td>
         PR generated → PR converted to PO → PO sent to vendor → Vendor
         supplies RM → MIGO (Goods Receipt) → Production → Quality Check
         → Unrestricted Stock → Order Confirmation → Delivery → Invoice →
         Customer pays
        </td>
       </tr>
      </tbody>
     </table>

     <h3>Scenario 3 — Full Step-by-Step Flow</h3>
     <div className="stepper">
      <div className="step">Customer places order.</div>
      <div className="step">
       System transfers requirements to MRP (Transfer of Requirements).
      </div>
      <div className="step">
       MRP runs → checks Finished Goods stock → not available.
      </div>
      <div className="step">
       System checks Raw Material stock → not available.
      </div>
      <div className="step">
       System automatically generates a PR (Purchase Requisition).
      </div>
      <div className="step">
       PR is converted to a PO (Purchase Order) → sent to vendor.
      </div>
      <div className="step">Vendor supplies the raw materials.</div>
      <div className="step">Goods Receipt is posted via MIGO.</div>
      <div className="step">
       Production begins → Quality Check → stock moves to Unrestricted
       Stock.
      </div>
      <div className="step">Order Confirmation → Delivery → Invoice.</div>
      <div className="step">
       Invoice is sent to the customer, who then makes payment.
      </div>
     </div>
    </div>

    {/* <!-- Section 3: OTC Integration & SD's Role --> */}
    <div className="card purple">
     <h2>
      <span className="badge">3</span> OTC — Cross-Module Integration &amp;
      SD's Role
     </h2>
     <div className="callout purple">
      💡 <strong>OTC is an integration across SD, MM, PP, and FI</strong>
      — all core modules are involved, unlike the plain Enquiry-to-Invoice
      sales cycle, which is SD-only.
     </div>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>Module</th>
        <th>Where It Comes In</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>SD (Sales &amp; Distribution)</td>
        <td>Order → Delivery → Invoice</td>
       </tr>
       <tr>
        <td>MM (Materials Management)</td>
        <td>MRP, PR/PO, vendor procurement, Goods Receipt (MIGO)</td>
       </tr>
       <tr>
        <td>PP (Production Planning)</td>
        <td>Production and Quality Check</td>
       </tr>
       <tr>
        <td>FI (Finance)</td>
        <td>Invoice posting and customer payment receipt</td>
       </tr>
      </tbody>
     </table>
     <div className="callout green">
      ✅ <strong>SD's specific role within the full OTC process:</strong>
      Order → Delivery → Invoice — the same three SD-owned stages,
      regardless of how much MM/PP activity happens in between.
     </div>
    </div>

    {/* <!-- Section 4: MRP Concept --> */}
    <div className="card red">
     <h2>
      <span className="badge">4</span> MRP Concept — T-codes MD01 &amp; MD02
     </h2>
     <div className="callout red">
      💡 <strong>MRP</strong> is a continuous, automatic background process
      — the system constantly checks Finished Goods stock and, where
      insufficient, checks the Raw Materials needed to produce it,
      generating a PR automatically wherever a shortfall exists.
     </div>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>T-Code</th>
        <th>Scope</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>MD01</td>
        <td>Run MRP for all materials (plant-wide)</td>
       </tr>
       <tr>
        <td>MD02</td>
        <td>Run MRP for a single, specific material</td>
       </tr>
      </tbody>
     </table>

     <h3>Worked Example — Finished Good X, Raw Materials A/B/C</h3>
     <div className="callout blue">
      📊 Manufacturing Finished Good X requires Raw Materials A, B, and C in
      fixed proportions. Monthly requirement of X = 20,000 units.
     </div>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>Raw Material</th>
        <th>Required for 20,000 units of X</th>
        <th>Available Stock</th>
        <th>MRP Result (MD02)</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>A</td>
        <td>40,000</td>
        <td>50,000</td>
        <td>Sufficient — no PR generated</td>
       </tr>
       <tr>
        <td>B</td>
        <td>30,000</td>
        <td>10,000</td>
        <td>Shortfall — PR automatically generated for B</td>
       </tr>
       <tr>
        <td>C</td>
        <td>35,000</td>
        <td>50,000</td>
        <td>Sufficient — no PR generated</td>
       </tr>
      </tbody>
     </table>
     <p className="note-text">
      📌 If X itself already has enough stock to cover the requirement, MRP
      does nothing for X at all — the raw-material check only triggers when
      the finished good's own stock falls short. Once a PR is generated (as
      for material B here), it follows the normal PR → PO → vendor supply →
      MIGO path before production can use it.
     </p>
    </div>

    {/* <!-- Section 5: Standard Sales Process Overview --> */}
    <div className="card gold">
     <h2>
      <span className="badge">5</span> Standard Sales Process — Overview
     </h2>
     <div className="callout gold">
      💡 The <strong>Standard Sales Process</strong> is the familiar SD-only
      cycle:
      <strong>Enquiry → Quotation → Sales Order → Delivery → Invoice</strong
      >.
     </div>
    </div>

    {/* <!-- Section 6: Enquiry --> */}
    <div className="card indigo">
     <h2><span className="badge">6</span> Standard Process — Enquiry</h2>
     <div className="callout indigo">
      💡 An <strong>Enquiry</strong> is created whenever a customer enquires
      about a product. It is an <strong>internal document</strong> — it is
      never sent to the customer.
     </div>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>Enquiry Document Consists Of</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>Customer Information</td>
       </tr>
       <tr>
        <td>Material Information</td>
       </tr>
       <tr>
        <td>Quantity Information</td>
       </tr>
      </tbody>
     </table>
    </div>

    {/* <!-- Section 7: Quotation --> */}
    <div className="card cyan">
     <h2><span className="badge">7</span> Standard Process — Quotation</h2>
     <div className="callout cyan">
      💡 After the Enquiry, a <strong>Quotation</strong> is created and
      <strong>sent to the customer</strong> as output (print/email). Unlike
      Enquiry, Quotation is an <strong>external document</strong> and a
      <strong>legal document</strong>.
     </div>
     <div className="callout red">
      ⚠️ <strong>Why it's a legal document:</strong> if the quotation is
      still valid (within its validity period) and quotes a specific price,
      the company must honor an order at that price even if costs rise
      afterward — refusal opens the door for the customer to raise the
      matter in consumer forum. If the validity period has lapsed, this
      protection no longer applies.
     </div>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>Quotation Document Consists Of</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>Customer Information</td>
       </tr>
       <tr>
        <td>Material Information</td>
       </tr>
       <tr>
        <td>Quantity Information</td>
       </tr>
       <tr>
        <td>Validity Period</td>
       </tr>
       <tr>
        <td>Terms and Conditions</td>
       </tr>
       <tr>
        <td>Pricing</td>
       </tr>
      </tbody>
     </table>
     <p className="note-text">
      📌 Terms and Conditions matter here too — e.g., a term stating that
      any future tax increase is payable by the customer means the "fixed
      price" legal protection doesn't cover tax changes, only the base
      price/terms actually quoted.
     </p>
    </div>

    {/* <!-- Section 8: Sales Order --> */}
    <div className="card green">
     <h2><span className="badge">8</span> Standard Process — Sales Order</h2>
     <div className="callout green">
      💡 If the customer is satisfied with the Quotation, they send a
      <strong>PO (Purchase Order) copy</strong> to the company. On receiving
      it, the company creates a
      <strong>Sales Order with reference to the Quotation</strong>.
     </div>
     <div className="callout blue">
      🔗 <strong>Definition:</strong> a Sales Order is an
      <strong
      >agreement between the company and the customer for supplying the
       goods</strong
      >.
     </div>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>Sales Order Consists Of</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>Customer Information</td>
       </tr>
       <tr>
        <td>Material Information</td>
       </tr>
       <tr>
        <td>Quantity Information</td>
       </tr>
       <tr>
        <td>
         PO Number (customer's own PO number, entered as a reference)
        </td>
       </tr>
       <tr>
        <td>Terms and Conditions</td>
       </tr>
       <tr>
        <td>Pricing</td>
       </tr>
       <tr>
        <td>Delivery Dates</td>
       </tr>
      </tbody>
     </table>
     <p className="note-text">
      📌 <strong>Worked example:</strong> if the customer's own Purchase
      Order number is <code>1001</code>, that same number is entered on the
      Sales Order purely for reference — it does not replace or generate the
      sales order's own document number.
     </p>
    </div>

    {/* <!-- Section 9: Sales Order Background Activities --> */}
    <div className="card pink">
     <h2>
      <span className="badge">9</span> Sales Order Creation — 11 Background
      Activities
     </h2>
     <div className="callout pink">
      💡 Creating a Sales Order triggers a chain of background activities in
      the system — 11 in total.
     </div>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>#</th>
        <th>Activity</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>1</td>
        <td>Partner Determination</td>
       </tr>
       <tr>
        <td>2</td>
        <td>Listing/Exclusion</td>
       </tr>
       <tr>
        <td>3</td>
        <td>Material Determination</td>
       </tr>
       <tr>
        <td>4</td>
        <td>Free Goods</td>
       </tr>
       <tr>
        <td>5</td>
        <td>Availability Check</td>
       </tr>
       <tr>
        <td>6</td>
        <td>Delivery Scheduling</td>
       </tr>
       <tr>
        <td>7</td>
        <td>Pricing</td>
       </tr>
       <tr>
        <td>8</td>
        <td>Credit Management</td>
       </tr>
       <tr>
        <td>9</td>
        <td>Tax Determination</td>
       </tr>
       <tr>
        <td>10</td>
        <td>Output Determination</td>
       </tr>
       <tr>
        <td>11</td>
        <td>Transfer of Requirements</td>
       </tr>
      </tbody>
     </table>
    </div>

    {/* <!-- Section 10: Delivery Preview --> */}
    <div className="card brown">
     <h2>
      <span className="badge">🔜</span> Coming Up — Delivery Activities
     </h2>
     <div className="callout brown">
      💡 Delivery consists of <strong>three activities</strong>:
      <strong>Picking, Packing, and PGI</strong> (Post Goods Issue) — to be
      covered in detail next class.
     </div>
    </div>

    {/* <!-- Extra: Interview Questions --> */}
    <div className="card purple">
     <h2>
      <span className="badge">❓</span> Important Interview Questions &amp;
      Answers
     </h2>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>Question</th>
        <th>Answer</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>
         What does OTC stand for, and how is it different from the plain
         Enquiry-to-Invoice sales cycle?
        </td>
        <td>
         Order to Cash — the complete cycle from order to payment,
         covering production and procurement across SD, MM, PP and FI,
         not just the SD-only sales document flow
        </td>
       </tr>
       <tr>
        <td>
         What are the three OTC scenarios based on stock availability?
        </td>
        <td>
         (1) FG stock available → straight to Order
         Confirmation/Delivery/Invoice; (2) FG unavailable but RM
         available → Production → Quality Check → Unrestricted Stock →
         onward; (3) Neither FG nor RM available → PR → PO → vendor
         supply → MIGO → Production → onward
        </td>
       </tr>
       <tr>
        <td>What do TOR, PR, PO, and MIGO stand for?</td>
        <td>
         TOR = Transfer of Requirements, PR = Purchase Requisition, PO =
         Purchase Order, MIGO = Movement In, Goods Out (Goods Receipt)
        </td>
       </tr>
       <tr>
        <td>
         Which modules are integrated in the OTC process, and what is
         SD's specific role?
        </td>
        <td>
         SD, MM, PP, and FI; SD's role is specifically Order → Delivery →
         Invoice
        </td>
       </tr>
       <tr>
        <td>What is the difference between MD01 and MD02?</td>
        <td>
         MD01 runs MRP for all materials at once; MD02 runs MRP for one
         specific material
        </td>
       </tr>
       <tr>
        <td>When does MRP automatically generate a PR?</td>
        <td>
         When a raw material's available stock is insufficient to meet
         the requirement calculated for the finished good it feeds into
        </td>
       </tr>
       <tr>
        <td>What is an Enquiry, and what does it contain?</td>
        <td>
         An internal document created when a customer enquires about a
         product; it is never sent to the customer and contains Customer,
         Material, and Quantity information
        </td>
       </tr>
       <tr>
        <td>Why is a Quotation called a legal document?</td>
        <td>
         A valid, unexpired quotation at a quoted price legally obligates
         the company to honor that price if the customer orders within
         the validity period — otherwise the customer could pursue the
         matter in consumer forum
        </td>
       </tr>
       <tr>
        <td>What does a Quotation document consist of?</td>
        <td>
         Customer information, material information, quantity
         information, validity period, terms and conditions, and pricing
        </td>
       </tr>
       <tr>
        <td>
         What triggers the creation of a Sales Order, and what is a Sales
         Order?
        </td>
        <td>
         Receiving a PO copy from the customer after they accept the
         quotation; a Sales Order is the agreement between company and
         customer for supplying the goods, created with reference to the
         quotation
        </td>
       </tr>
       <tr>
        <td>What does a Sales Order consist of?</td>
        <td>
         Customer information, material information, quantity
         information, the customer's PO number (for reference), terms and
         conditions, pricing, and delivery dates
        </td>
       </tr>
       <tr>
        <td>
         How many background activities happen when a Sales Order is
         created, and name a few?
        </td>
        <td>
         11 — including Partner Determination, Availability Check,
         Pricing, Credit Management, Tax Determination, Output
         Determination, and Transfer of Requirements
        </td>
       </tr>
       <tr>
        <td>What are the three activities within Delivery?</td>
        <td>Picking, Packing, and PGI (Post Goods Issue)</td>
       </tr>
      </tbody>
     </table>
    </div>

    {/* <!-- Extra: T-codes --> */}
    <div className="card teal">
     <h2>
      <span className="badge">🔢</span> Important Transaction Codes &amp;
      Purpose
     </h2>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>T-Code</th>
        <th>Purpose</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td><span className="tcode">MD01</span></td>
        <td>Run MRP for all materials in a plant</td>
       </tr>
       <tr>
        <td><span className="tcode">MD02</span></td>
        <td>Run MRP for one specific material</td>
       </tr>
       <tr>
        <td><span className="tcode">MIGO</span></td>
        <td>
         Post Goods Receipt when raw materials are received from a vendor
        </td>
       </tr>
      </tbody>
     </table>
    </div>

    {/* <!-- Extra: Config Topics --> */}
    <div className="card gold">
     <h2>
      <span className="badge">⚙️</span> Important Configuration Topics &amp;
      Values
     </h2>
     <table className="table-reponsive">
      <thead>
       <tr>
        <th>Topic</th>
        <th>Value / Detail</th>
       </tr>
      </thead>
      <tbody>
       <tr>
        <td>MRP worked example — Finished Good X</td>
        <td>
         Monthly requirement 20,000 units; Raw Materials A (40,000
         req/50,000 stock), B (30,000 req/10,000 stock — PR generated), C
         (35,000 req/50,000 stock)
        </td>
       </tr>
       <tr>
        <td>Sales Order reference example</td>
        <td>
         Customer PO number 1001 entered on Sales Order for reference
         only
        </td>
       </tr>
       <tr>
        <td>Sales Order background activities count</td>
        <td>
         11 activities (Partner Determination through Transfer of
         Requirements)
        </td>
       </tr>
       <tr>
        <td>Delivery activities count</td>
        <td>3 activities — Picking, Packing, PGI</td>
       </tr>
      </tbody>
     </table>
    </div>

    {/* <!-- Extra: Summary --> */}
    <div className="card">
     <h2><span className="badge">📝</span> Summary</h2>
     <p>
      This lecture introduced the
      <strong>OTC (Order to Cash) process</strong> as the complete,
      cross-module cycle from customer order to payment, walking through its
      three stock-availability scenarios (FG available; FG unavailable/RM
      available; neither available — triggering PR → PO → vendor → MIGO),
      and clarifying that OTC integrates SD, MM, PP, and FI, with SD's own
      role confined to Order → Delivery → Invoice. It then explained the
      <strong>MRP concept</strong> as a continuous automatic background
      process (run plant-wide via MD01 or per material via MD02),
      illustrated with a worked Finished Good X / Raw Materials A-B-C
      example showing exactly when a PR gets auto-generated. The lecture
      then returned to the familiar <strong>Standard Sales Process</strong>,
      detailing <strong>Enquiry</strong> (internal document — customer,
      material, quantity info), <strong>Quotation</strong> (external and
      legal document — adds validity period, terms and conditions, and
      pricing, with real legal weight if the company doesn't honor a valid
      quote), and <strong>Sales Order</strong> (created on receiving the
      customer's PO copy, with reference to the quotation — an agreement to
      supply goods, carrying the customer's PO number for reference). It
      closed with the <strong>11 background activities</strong> triggered at
      Sales Order creation and a preview of Delivery's three activities —
      Picking, Packing, and PGI — for the next class.
     </p>
    </div>

    {/* <!-- Best Practice / Next Class --> */}
    <div className="card">
     <h2>
      <span className="badge">⭐</span> Key Takeaways &amp; Next Class
     </h2>
     <ul>
      <li>
       <strong>OTC is the "big picture" process</strong> — the
       Enquiry-to-Invoice cycle taught earlier is really just the SD slice
       of this larger, cross-module flow
      </li>
      <li>
       <strong>MRP is fully automatic and continuous</strong> — PR
       generation isn't a manual decision, it's the system's own reaction
       to a calculated raw-material shortfall
      </li>
      <li>
       <strong
       >Enquiry (internal) vs. Quotation (external, legal) vs. Sales
        Order (agreement)</strong
       >
       — each step up the chain adds legal and commercial weight; know the
       distinction cold
      </li>
      <li>
       The customer's
       <strong>PO number on a Sales Order is reference-only</strong> — it
       never substitutes for or drives the sales order's own numbering
      </li>
      <li>
       <strong
       >11 background activities fire at Sales Order creation</strong
       >
       — a useful checklist for understanding what "creating an order"
       actually triggers under the hood
      </li>
     </ul>
     <div className="callout green">
      📅 <strong>Next class:</strong> Delivery activities — Picking,
      Packing, and PGI — in detail.
     </div>
    </div>
   </div>
   <p className="footer-note">
    Lecture 41 Notes — OTC Process, MRP Concept &amp; Standard Sales Process
    🎓
   </p>
  </div>
 );
};

export default Business41;
